export default [
  { name: "3Portals", logo: "./src/assets/Customer-icons/3Portals.svg" },
  { name: "45 Degrees", logo: "./src/assets/Customer-icons/45 Degrees.svg" },
  { name: "Acme Corp", logo: "./src/assets/Customer-icons/Acme Corp.svg" },
  { name: "AlphaWave", logo: "./src/assets/Customer-icons/AlphaWave.svg" },
  { name: "Alt+Shift", logo: "./src/assets/Customer-icons/Alt+Shift.svg" },
  { name: "Biosynthesis", logo: "./src/assets/Customer-icons/Biosynthesis.svg" },
  { name: "Boltshift", logo: "./src/assets/Customer-icons/Boltshift.svg" },
  { name: "BuildingBlocks", logo: "./src/assets/Customer-icons/BuildingBlocks.svg" },
  { name: "Calescence", logo: "./src/assets/Customer-icons/Calescence.svg" },
  { name: "Capsule", logo: "./src/assets/Customer-icons/Capsule.svg" },
  { name: "Catalog", logo: "./src/assets/Customer-icons/Catalog.svg" },
  { name: "Chromatools", logo: "./src/assets/Customer-icons/Chromatools.svg" },
  { name: "Clandestine", logo: "./src/assets/Customer-icons/Clandestine.svg" },
  { name: "CloudWatch", logo: "./src/assets/Customer-icons/CloudWatch.svg" },
  { name: "Codecraft", logo: "./src/assets/Customer-icons/Codecraft_.svg" },
  { name: "Command+R", logo: "./src/assets/Customer-icons/Command+R.svg" },
  { name: "Constellation", logo: "./src/assets/Customer-icons/Constellation.svg" },
  { name: "ContrastAI", logo: "./src/assets/Customer-icons/ContrastAI.svg" },
  { name: "Convergence", logo: "./src/assets/Customer-icons/Convergence.svg" },
  { name: "Cooperative", logo: "./src/assets/Customer-icons/Cooperative.svg" },
  { name: "CoreOS", logo: "./src/assets/Customer-icons/CoreOS.svg" },
  { name: "Cubekit", logo: "./src/assets/Customer-icons/Cubekit.svg" },
  { name: "EasyTax", logo: "./src/assets/Customer-icons/EasyTax.svg" },
  { name: "Eclipseful", logo: "./src/assets/Customer-icons/Eclipseful.svg" },
  { name: "Eightball", logo: "./src/assets/Customer-icons/Eightball.svg" },
  { name: "Elasticware", logo: "./src/assets/Customer-icons/Elasticware.svg" },
  { name: "ennLabs", logo: "./src/assets/Customer-icons/ennLabs.svg" },
  { name: "Ephemeral", logo: "./src/assets/Customer-icons/Ephemeral.svg" },
  { name: "Epicurious", logo: "./src/assets/Customer-icons/Epicurious.svg" },
  { name: "Gucci", logo: "./src/assets/Customer-icons/Gucci.png" },
  {name: "coca-cola",logo:"./src/assets/Customer-icons/coca-cola.png" },
  {name: "hm", logo:"./src/assets/Customer-icons/hm.png"},
  {name: "puma",  logo:"./src/assets/Customer-icons/Puma.png"},
  {name: "versace", logo:"./src/assets/Customer-icons/Versace.png"},
  {name: "starbuck", logo:"./src/assets/Customer-icons/Starbuck.png"},
  {name: "hyundai", logo:"./src/assets/Customer-icons/Hyundai.png"},
  {name: "versace", logo:"./src/assets/Customer-icons/Versace.png"},
  {name: "rage", logo:"./src/assets/Customer-icons/Rage.png"},
  {name: "vl", logo:"./src/assets/Customer-icons/Vl.png"},
  {name: "double", logo:"./src/assets/Customer-icons/Double.png"},
  {name: "chanel", logo:"./src/assets/Customer-icons/Chanel.png"},

                                                     

];
